name: Test Github Action

on:
  push:
  pull_request:

jobs:

  action:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pre-pull Docker image for ghdl/vunit:llvm-master
        run: docker pull ghdl/vunit:llvm-master

      - name: Run VUnit tests
        uses: VUnit/vunit_action@master
        with:
          cmd: python3 run.py --xunit-xml test_output.xml
          image: ghdl/vunit:llvm-master
          #args: python3 run.py

      - name: Upload simulation results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: simulation-artifacts (action)
          path: test_output.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/test_output.xml"
          include_passed : true
          #annotate_only : true
          check_annotations : true
          detailed_summary : true
          check_name : VUnit Test Report (mikepenz)

  container-job:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    container: ghdl/vunit:mcode-master
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run VUnit tests
        run: python3 run.py --xunit-xml vunit_results.xml

      - name: Upload simulation results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: simulation-artifacts (container)
          path: vunit_results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/*.xml"
          check_name: VUnit Test Report (EnricoMi)
