name: Test Github Action

on:
  push:
  pull_request:

jobs:

  action:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Run VUnit tests
        uses: VUnit/vunit_action@v0.1.0
        with:
          #cmd: sh -c "python3 run.py" -x report.xml
          args: python3 run.py
      #- name: Publish Test Results
      #  if: always()
      #  uses: dorny/test-reporter@v1
      #  with:
      #    name: VUnit Tests
      #    path: report.xml
      #    reporter: junit

  container-job:
    runs-on: ubuntu-latest
    container: ghdl/vunit:mcode-master
    steps:
    - uses: actions/checkout@v4
    - run: python3 run.py
