name: Test Github Action

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        uses: VUnit/vunit_action@master
        uses: ./
        with:
          cmd: run.py

  container-job:
    runs-on: ubuntu-latest
    container: ghdl/vunit:mcode-master
    steps:
    - uses: actions/checkout@v2
    - run: run.py
