name: Test Github Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run VUnit tests
        uses: VUnit/vunit_action@master
        with:
          cmd: sh -c "python3 run.py"
