name: Test Github Action

on:
  push:
  pull_request:

jobs:

  action:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run VUnit tests
        uses: VUnit/vunit_action@master
        with:
          cmd: sh -c "python3 run.py"

  container-job:
    runs-on: ubuntu-latest
    container: ghdl/vunit:mcode-master
    steps:
    - uses: actions/checkout@v2
    - run: run.py
